version: '3.6'
services:
  # flask:
  #   restart: always
  #   build: .
  #   expose:
  #     - "5000"
  #   ports:
  #     - "5000:5000"
  #   links:
  #     - postgres:postgres
  #   volumes:
  #     - flask-volume:/usr/src/app/static
  #   env_file:
  #     - .env
  # postgres:
  #   image: postgres:12
  #   restart: always
  #   volumes:
  #   - db_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #   - "25775:5432"
  graphql-engine:
    image: fedormelexin/graphql-engine-arm64
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/odoo
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
volumes:
  db_data:
  flask-volume: